---
title: "David's initial exploration"
author: "David Lovell"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
# Set options to control the behaviour of knitr, dplyr, etc
knitr::opts_chunk$set(echo = FALSE, comment=NA, warning = FALSE, message = FALSE)
options(knitr.table.format = "html", dplyr.summarise.inform = FALSE, tidyverse.quiet = TRUE, width = 100)
```

## Indexing rows and columns in our data

* $i$ is the (row) index of each compositional observation
* $j$ and $k$ are the used to index different components (columns)


## Actual and predicted component proportions

* $a_{ij}$ is the _actual_ proportion of component $j$ in composition $i$
* $p_{ij}$ is the _predicted_ proportion of component $j$ in composition $i$
  * I'm going to leave out the index of the model making that prediction... already got enough subscripts!
  
## Additive residuals

* $r_{ij} = p_{ij} - a_{ij}$ is the additive residual of component $j$ in composition $i$
  * If $r_{ij} < 0$, we have underestimated the abundance of that component
  * If $r_{ij} = 0$, we have correctly estimated the abundance of that component
  * If $r_{ij} > 0$, we have overestimated the abundance of that component

## Multiplicative residuals

* $r_{ij} = \frac{p_{ij}}{a_{ij}}$ is the _multiplicative residual of component $j$ in composition $i$
  * If $r_{ij} < 1$, we have underestimated the abundance of that component
  * If $r_{ij} = 1$, we have correctly estimated the abundance of that component
  * If $r_{ij} > 1$, we have overestimated the abundance of that component
  
  
I write

* $a_{ij/k} = \frac{a_{ij}}{a_{ik}}$, the ratio of _actual_ components $j$ and $k$ in composition $i$
* $p_{ij/k} = \frac{p_{ij}}{p_{ik}}$, the ratio of _predicted_ components $j$ and $k$ in composition $i$
* $r_{ijk} = \frac{p_{ij/k}}{a_{ij/k}}$, is the multiplicative residual of components $j$ and $k$ in composition $i$

I'm interested to plot how well different models estimate the _ratios_ of components. My plan is to plot $r_{ijk}$ vs $p_{ij/k}$ for each model.
