---
title: "CoDa Model Evaluation"
author: "Nicholas Gecks-Preston"
output:
  html_document:
    df_print: paged
  html:
    embed-resources: yes
editor: source
---

```{r setup, include=FALSE}
# This chunk is for the document and package setup

## Clear the Workspace
rm(list = ls())
if (length((.packages())) > 7){
invisible(lapply(paste0("package:", names(sessionInfo()$otherPkgs)),   # Unload add-on packages
                 detach,
                 character.only = TRUE, unload = TRUE))
}

## Setup Packages + Knit
knitr::opts_chunk$set(echo = FALSE, comment=NA, warning = FALSE)
pckgs <- c("tidyverse", "plotly", "broom", "readr")
lapply(pckgs, require, character.only = TRUE)
rm(list = ls())
```

```{r, include=FALSE, eval=FALSE}
# Use this to Read the Data in

holder <- list.files(pattern = "*.csv")
data <- sapply(holder, read.csv)
rm("holder")

```

```{r, include=TRUE}
test <- read.csv("method_1.csv")

hold2 <- matrix(, nrow = 10, ncol = nrow(test))
for (k in 1:nrow(test)) {
hold2[,k] = unlist(strsplit(test[k, 1], "\t"))
}
hold2 = t(hold2)
df1 = data.frame(ID = hold2[,1], A = hold2[,2], B = hold2[,3], C = hold2[,4], D = hold2[,5], E = hold2[,6], F = hold2[,7], G = hold2[,8], H = hold2[,9], I =hold2[,10])


test2 <- read.csv("truth.csv")

hold3 <- matrix(, nrow = 10, ncol = nrow(test2))
for (k in 1:nrow(test2)) {
hold3[,k] = unlist(strsplit(test2[k, 1], "\t"))
}
hold3 = t(hold3)
df2 = data.frame(ID = hold3[,1], A = hold3[,2], B = hold3[,3], C = hold3[,4], D = hold3[,5], E = hold3[,6], F = hold3[,7], G = hold3[,8], H = hold3[,9], I =hold3[,10])

df3 = data.frame(A_est = hold2[,2], A_true = hold3[,2])




```


```{r, include=TRUE}

ggplot(data = df3, mapping = aes(x = A_true ,y = A_est)) +
  geom_point()

```



dgf

### Required Packages
1. tidyverse
2. plotly 
3. broom
4. readr
